# Install go-task: taskfile.dev
#   brew install go-task/tap/go-task
---
version: "3"

tasks:
  build:
    desc: Build the container
    silent: true
    sources:
      - main.py
    cmds:
      - docker build -t randomized_picker:latest .

  run:
    desc: Run the picker
    silent: true
    deps: [ build ]
    cmds:
      - docker run -it --rm randomized_picker:latest